# 头部导航 Header
menu:
  首页: /
  归档: /archives
  关于: /about
  项目: /project
  github: https://github.com/WilsonLiu95
# 内容 Content
excerpt_link: 继续阅读全文 »
fancybox: false

# 侧边栏 Sidebar
sidebar: right
widgets:
- about
- motto
- category
- tagcloud
- recent_posts
# - lastest_comments
- hot_comment_posts
- archive
- links

# 提供以下 7 个内置组件
# - category          # 归类
# - tag               # 标签
# - tagcloud          # 云标签
# - archives          # 归档
# - recent_posts      # 最新文章
# - lastest_comments  # 最新评论
# - hot_comment_posts # 热评文章

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# 标签云TagClound
# 如果启动，则标签云颜色为随机
tagcloud_color: true 
#打赏
donate:
  enable: true
  text: 欣赏此文？求鼓励，求支持！
  wechat: http://wilsonliu.cn/cdn/img/201612/ce0b7da9bb31110c162ba7aa881daa43.JPG
  alipay: http://wilsonliu.cn/cdn/img/201612/68a5f2d6f53cf54496e1d98985e15c10.JPG


# 其他参数
baidu_analytics: fc8ddbf1bcbb18a7b8c1f9979eed0900
favicon: http://wilsonliu.cn/favicon.ico
# 若使用多说，此处填写的是多说评论账号ID
# 若使用Disqus，请在博客 config 文件中填写disqus_shortname，并设置duosuo: false关闭多说评论
duoshuo_shortname: wilsonliu95
google_plus:
fb_admins:
fb_app_id:
